### ISSUE TITLE
Add Accordion Component

### ISSUE THREAD

**Issue by touhidrahman** [koobiq/angular-components#352]
**I'm submitting a**

-   [ ] bug
-   [x] feature request
-   [ ] question

**What is the current behavior?**
Not available

**If the current behavior is a bug, please provide the steps to reproduce it**
N/A

**What is the expected behavior?**
Accordions are common in web applications. It holds a series of titles and some content under each of them. The contents may initially be collapsed. Clicking on the title will expand the content area. An example: https://ui.shadcn.com/docs/components/accordion

**Please tell us about your environment:**

-   koobiq version: x.x.x
-   Browser: [all | Chrome XX | Firefox XX | Edge XX | Safari XX ]

**Other information**

**Comment by pimenovoleg** [comment]
@touhidrahman 
We are actually about to merge the implementation in just a couple of days! :)
